#include "common/qlu.h"

#include <cstdlib>

#include "common/convert.h"
#include "common/oii_gemm.h"
#include "common/definitions.h"
#include "common/error.h"
#include "common/timing.h"

/*  int8lu.cuh calls std::sort without including <algorithm>; upstream never
    saw it because its one driver includes <algorithm> first. Vendor files are
    kept verbatim, so the include goes here. */
#include <algorithm>
#include <vector>

#include "df32_kernels.cuh"
#include "df_ext_b4.cuh"

/*  LPS_DUMP builds this TU against an INSTRUMENTED copy of the vendor
    header, generated by tools/instrument_int8lu.py, so the export
    harness can record the factorization's per-step state. The vendor
    tree stays byte-identical to the import either way; what changes is
    which copy this one TU compiles against.

    The object is built twice -- qlu.o for every normal binary and
    qlu_dump.o for lps-lift-dump -- because two TUs including the
    vendor header in one binary is a duplicate symbol at device link. */
#ifdef LPS_DUMP
#include "int8lu_instrumented.cuh"
#else
#include "int8lu.cuh"
#endif

namespace qlu {

namespace {

/*  out = in[perm[.]], applying the row permutation to a DF32 vector. */
__global__ void gather_kernel(
    int const         n,
    int const        *perm,
    float const      *in_hi,
    float const      *in_lo,
    float            *out_hi,
    float            *out_lo) {

    int const i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= n)
        return;

    out_hi[i] = in_hi[perm[i]];
    out_lo[i] = in_lo[perm[i]];
}

/*  x += d, both DF32. The IR update, carried in the wide format so the
    correction's trailing digits survive. */
__global__ void add_correction_kernel(
    int const    n,
    float const *d_hi,
    float const *d_lo,
    float       *x_hi,
    float       *x_lo) {

    int const i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= n)
        return;

    df32 const r = df_add(df_make(x_hi[i], x_lo[i]), df_make(d_hi[i], d_lo[i]));
    x_hi[i] = r.hi;
    x_lo[i] = r.lo;
}

/*  max |v|, as atomicMax on the float bit pattern. Valid because the values
    compared are magnitudes: IEEE ordering is monotonic on non-negatives. */
__global__ void max_abs_kernel(
    int const    n,
    float const *v,
    float       *out) {

    __shared__ float s[launch::BLOCK_SIZE];

    int const t = threadIdx.x;
    float m = 0.f;
    for (int i = blockIdx.x * blockDim.x + t; i < n;
         i += blockDim.x * gridDim.x)
        m = fmaxf(m, fabsf(v[i]));

    s[t] = m;
    __syncthreads();

    for (int q = blockDim.x / 2; q > 0; q >>= 1) {
        if (t < q)
            s[t] = fmaxf(s[t], s[t + q]);
        __syncthreads();
    }

    if (t == 0)
        atomicMax(reinterpret_cast<int *>(out), __float_as_int(s[0]));
}

/*  Output boundary: the only place a DF32 value becomes an fp64 one. */
__global__ void combine_kernel(
    int const    n,
    float const *x_hi,
    float const *x_lo,
    double      *x) {

    int const i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        x[i] = static_cast<double>(x_hi[i]) + static_cast<double>(x_lo[i]);
}

} /* anonymous namespace */

struct state {

    std::size_t    n       = 0;
    int            b       = 0;
    int            kfac    = 0;
    kernel         which   = kernel::sliced;
    oii::state    *oii_s   = nullptr;

    /*  S-rung diagonal-block inverses, n*IB floats each, built once per
        factorization. Null when srung_ib is 0. */
    int    srung_ib = 0;
    float *d_dlh = nullptr, *d_dll = nullptr;
    float *d_duh = nullptr, *d_dul = nullptr;
    cublasHandle_t blas    = nullptr;
    Int8LUScratch  scratch = {};

    /*  Residual operator and carrier, both row-major DF32. Distinct because
        the factorization consumes the carrier. */
    float *d_ah = nullptr, *d_al = nullptr;
    float *d_hi = nullptr, *d_lo = nullptr;

    int *d_piv  = nullptr;   /* getrf-style interchanges                 */
    int *d_perm = nullptr;   /* composed permutation, host-built         */

    /*  Solve workspace. */
    std::size_t rhs_cap = 0;     /* columns the solve workspace holds */

    /*  GMRES-IR workspace: the Arnoldi basis (j+1 blocks of n x k), the
        Hessenberg store, and the small per-column scalars. Allocated on
        first use at a given (j, k). */
    int    gm_j = 0;
    std::size_t gm_k = 0;
    float *gm_vh = nullptr, *gm_vl = nullptr;   /* (j+1) * n * k */
    float *gm_wh = nullptr, *gm_wl = nullptr;   /* n * k         */
    float *gm_th = nullptr, *gm_tl = nullptr;   /* n * k scratch */
    float *gm_uh = nullptr, *gm_ul = nullptr;   /* n * k scratch */
    float *gm_hh = nullptr, *gm_hl = nullptr;   /* k*(j+1)*j     */
    float *gm_yh = nullptr, *gm_yl = nullptr;   /* k*j           */
    float *gm_sh = nullptr, *gm_sl = nullptr;   /* k scalars     */
    float *gm_bh = nullptr, *gm_bl = nullptr;   /* k betas       */
    int   *gm_keff = nullptr;                   /* k             */
    float *d_bh = nullptr, *d_bl = nullptr;
    float *d_xh = nullptr, *d_xl = nullptr;
    float *d_rh = nullptr, *d_rl = nullptr;
    float *d_yh = nullptr, *d_yl = nullptr;
    float *d_zh = nullptr, *d_zl = nullptr;
    float *d_th = nullptr, *d_tl = nullptr;
    float *d_nrm = nullptr;

    std::vector<void *> owned;

    /*  Phase markers. One event per boundary, synchronized once at the end,
        so the breakdown costs a record per phase and no serialization. */
    std::vector<cudaEvent_t> marks;
    std::size_t              n_marks = 0;
    phase_times              times   = {};

    /*  Phase each span ENDS in; -1 opens the sequence. Tagging rather than
        assuming a fixed stride per iteration, because the loop can exit at
        the convergence test with only part of an iteration recorded. */
    std::vector<int> tags;

    cudaEvent_t mark(int const phase) {
        if (n_marks < tags.size()) tags[n_marks] = phase;
        else                       tags.push_back(phase);
        if (n_marks == marks.size()) {
            cudaEvent_t e = nullptr;
            CUDA_CHECK(cudaEventCreate(&e));
            marks.push_back(e);
        }
        cudaEvent_t const e = marks[n_marks++];
        CUDA_CHECK(cudaEventRecord(e));
        return e;
    }

    /*  Sum the spans by tag. Call after a synchronization. */
    void fold(double *bucket[]) {
        for (std::size_t i = 1; i != n_marks; ++i)
            if (tags[i] >= 0)
                *bucket[tags[i]] += span(i - 1, i);
        n_marks = 0;
    }

    double span(std::size_t const a, std::size_t const b) const {
        float ms = 0.f;
        CUDA_CHECK(cudaEventElapsedTime(&ms, marks[a], marks[b]));
        return static_cast<double>(ms);
    }

    void *acquire(std::size_t const bytes) {
        void *p = nullptr;
        if (!CUDA_CHECK(cudaMalloc(&p, bytes)))
            return nullptr;
        owned.push_back(p);
        return p;
    }
};

state *create(
    std::size_t const n,
    int const         b,
    int const         kfac,
    kernel const      which,
    int const         srung_ib) {

    if (srung_ib != 0 && (srung_ib <= 0 || n % srung_ib != 0)) {
        std::fprintf(stderr, "[qlu] srung_ib=%d does not divide n=%zu\n",
                     srung_ib, n);
        return nullptr;
    }

    /*  CLAMP THE PANEL WIDTH BEFORE ANYTHING ALLOCATES.

        int8lu_scratch_alloc computes `size_t M = (size_t)(n - b)` from
        two ints. With b > n that is negative, wraps to about 2^64, and
        the cudaMalloc that follows asks for a nonsense size. Upstream
        never sees it because int8lu_factor clamps `if(b<=0||b>n) b=n`
        -- but that clamp is inside the FACTOR, which runs long after
        the scratch is allocated, so the wrapper has to do it here.

        Found by a boundary test in lps-consistency, which triggered it
        rather than reporting it: the machine became unreachable during
        the run. The clamp matches the vendor's own rule so the
        factorization behaves identically; what changes is that the
        allocation is sane. */
    /*  LPS_SR=1 selects keyed stochastic rounding for every arm in the
        process, matching how FUSE/ASYNC and the rest of this codebase's
        knobs are set. Read here so a binary that never heard of the
        flag still honours it; explicit set_rounding calls override it
        and the gates use those. */
    {
        static bool once = false;
        if (!once) {
            once = true;
            char const *e = std::getenv("LPS_SR");
            if (e != nullptr && e[0] == '1')
                set_rounding(rounding::stochastic);
        }
    }

    int b_use = b;
    if (b_use <= 0 || static_cast<std::size_t>(b_use) > n)
        b_use = static_cast<int>(n);

    state *s = new state;
    s->n        = n;
    s->b        = b_use;
    s->kfac     = kfac;
    s->which    = which;
    s->srung_ib = srung_ib;

    if (!CUBLAS_CHECK(cublasCreate(&s->blas))) {
        delete s;
        return nullptr;
    }

    std::size_t const nn = n * n;
    s->d_ah = static_cast<float *>(s->acquire(nn * sizeof(float)));
    s->d_al = static_cast<float *>(s->acquire(nn * sizeof(float)));
    s->d_hi = static_cast<float *>(s->acquire(nn * sizeof(float)));
    s->d_lo = static_cast<float *>(s->acquire(nn * sizeof(float)));

    s->d_piv  = static_cast<int *>(s->acquire(n * sizeof(int)));
    s->d_perm = static_cast<int *>(s->acquire(n * sizeof(int)));

    float **const work[] = {&s->d_bh, &s->d_bl, &s->d_xh, &s->d_xl,
                            &s->d_rh, &s->d_rl, &s->d_yh, &s->d_yl,
                            &s->d_zh, &s->d_zl, &s->d_th, &s->d_tl};
    for (std::size_t i = 0; i != sizeof work / sizeof *work; ++i)
        *work[i] = static_cast<float *>(s->acquire(n * sizeof(float)));

    s->d_nrm = static_cast<float *>(s->acquire(sizeof(float)));

    if (srung_ib != 0) {
        std::size_t const nb = n * static_cast<std::size_t>(srung_ib)
                             * sizeof(float);
        s->d_dlh = static_cast<float *>(s->acquire(nb));
        s->d_dll = static_cast<float *>(s->acquire(nb));
        s->d_duh = static_cast<float *>(s->acquire(nb));
        s->d_dul = static_cast<float *>(s->acquire(nb));
        if (s->d_dul == nullptr) {
            destroy(s);
            return nullptr;
        }
    }

    int8lu_scratch_alloc(s->scratch, static_cast<int>(n), b_use, kfac);

    if (which == kernel::oii) {
        /*  Sized for the first trailing update, which is the largest;
            every later one is smaller and passes its own m and n.

            n <= b means the whole matrix is one panel and there is no
            trailing update at all. Guarded because `n - b` is computed
            in size_t and would wrap to an enormous allocation rather
            than fail. */
        if (n <= static_cast<std::size_t>(b_use)) {
            std::fprintf(stderr, "[qlu] oii arm needs n > b "
                                 "(n=%zu b=%d): no trailing update\n",
                         n, b_use);
            destroy(s);
            return nullptr;
        }
        s->oii_s = oii::create(n - static_cast<std::size_t>(b_use), b_use,
                               n - static_cast<std::size_t>(b_use), kfac);
        if (s->oii_s == nullptr) {
            destroy(s);
            return nullptr;
        }
    }
    return s;
}

void destroy(state *s) {

    if (s == nullptr)
        return;

    oii::destroy(s->oii_s);

    for (std::size_t i = 0; i != s->marks.size(); ++i)
        CUDA_CHECK(cudaEventDestroy(s->marks[i]));

    int8lu_scratch_free(s->scratch);
    for (std::size_t i = 0; i != s->owned.size(); ++i)
        CUDA_CHECK(cudaFree(s->owned[i]));
    if (s->blas != nullptr)
        CUBLAS_CHECK(cublasDestroy(s->blas));

    delete s;
}

void prepare(
    state        *s,
    double const *d_a) {

    if (s == nullptr)
        return;

    std::size_t const nn = s->n * s->n;

    /*  One transpose+split into the residual operator, then a straight copy
        into the carrier: the two hold the same matrix and only the carrier
        is destroyed. */
    s->times = phase_times();
    s->n_marks = 0;
    s->mark(-1);

    convert::transpose_split_df32(s->d_ah, s->d_al, d_a, s->n);
    CUDA_CHECK(cudaMemcpy(s->d_hi, s->d_ah, nn * sizeof(float),
                          cudaMemcpyDeviceToDevice));
    CUDA_CHECK(cudaMemcpy(s->d_lo, s->d_al, nn * sizeof(float),
                          cudaMemcpyDeviceToDevice));

    s->mark(0);
    CUDA_CHECK(cudaDeviceSynchronize());
    s->times.prepare += s->span(0, 1);
    s->n_marks = 0;
}

/*  ---- GMRES-IR(j) ----------------------------------------------------

    Outer refinement whose correction equation A d = r is solved by j
    GMRES steps, LEFT-preconditioned by B0^-1 = U^-1 L^-1 P, from x0 = 0.
    That is the setting of the core's outer-step theorem, and it matches
    core_exp/ir.py::gmres_ir, which is the reference this is gated
    against.

    WHY THE BATCHED TRSM WAS A PREREQUISITE. Arnoldi steps are
    sequentially dependent: step i+1 needs the vector step i produced, so
    there is nothing to batch WITHIN one system's inner solve. What
    batches is step i of all k right-hand sides, which is one call to
    trsv_*_mrhs over k columns. Without that, GMRES-IR(j) on k systems
    costs j*k triangular solves; with it, j.

    Everything is DF32. The (j+1) x j least squares runs on the device,
    one thread per column -- j <= 8, so the work is nothing, and keeping
    it there avoids an fp64 island on the host and a sync inside the
    Arnoldi loop. */

/*  DF32 square root: one Newton step on the fp32 seed, which takes ~24
    bits to ~48 and is what the pair holds. */
__device__ __forceinline__ df32 df_sqrt(df32 const a) {

    if (a.hi <= 0.f)
        return df_make(0.f, 0.f);
    float const r0 = sqrtf(a.hi);
    df32 const q = df_div(a, df_make(r0, 0.f));
    df32 const s = df_add_acc(df_make(r0, 0.f), q);
    return df_mul(s, df_make(0.5f, 0.f));
}

/*  Elementwise DF32 sqrt of k scalars. */
__global__ void k_df_sqrt_scalars(
    int const nrhs, float const *ih, float const *il,
    float *oh, float *ol) {

    int const c = blockIdx.x * blockDim.x + threadIdx.x;
    if (c >= nrhs)
        return;
    df32 const r = df_sqrt(df_make(ih[c], il[c]));
    oh[c] = r.hi;
    ol[c] = r.lo;
}

/*  y += Y[c*j + i] * x, the coefficient taken from the least squares. */
__global__ void k_df_axpy_strided(
    int const n, int const nrhs, int const ld, int const j, int const i,
    float const *ch, float const *cl,
    float const *xh, float const *xl,
    float *yh, float *yl) {

    int const q = blockIdx.x * blockDim.x + threadIdx.x;
    int const c = blockIdx.y;
    if (q >= n || c >= nrhs)
        return;
    std::size_t const o = static_cast<std::size_t>(c) * ld + q;
    std::size_t const e = static_cast<std::size_t>(c) * j + i;
    df32 const r = df_add_acc(df_make(yh[o], yl[o]),
                              df_mul(df_make(ch[e], cl[e]),
                                     df_make(xh[o], xl[o])));
    yh[o] = r.hi;
    yl[o] = r.lo;
}

/*  Deterministic DF32 dot per column: one block, fixed-order tree, so
    the result does not depend on how the blocks happened to schedule.
    Reproducibility is the reason the vendored reductions are written
    this way and the reason this one is too. */
__global__ void k_df_dot_mrhs(
    int const    n,
    int const    ld,
    float const *xh,
    float const *xl,
    float const *yh,
    float const *yl,
    float       *oh,
    float       *ol) {

    __shared__ float sh[256], sl[256];
    std::size_t const off = static_cast<std::size_t>(blockIdx.x) * ld;
    int const t = threadIdx.x;

    df32 acc = df_make(0.f, 0.f);
    for (int i = t; i < n; i += blockDim.x)
        acc = df_add_acc(acc, df_mul(df_make(xh[off + i], xl[off + i]),
                                     df_make(yh[off + i], yl[off + i])));
    sh[t] = acc.hi;
    sl[t] = acc.lo;
    __syncthreads();
    for (int o = blockDim.x >> 1; o > 0; o >>= 1) {
        if (t < o) {
            df32 const v = df_add_acc(df_make(sh[t], sl[t]),
                                      df_make(sh[t + o], sl[t + o]));
            sh[t] = v.hi;
            sl[t] = v.lo;
        }
        __syncthreads();
    }
    if (t == 0) {
        oh[blockIdx.x] = sh[0];
        ol[blockIdx.x] = sl[0];
    }
}

/*  y += s * a[col] * x, the scalar read from device so the Arnoldi loop
    never synchronizes. */
__global__ void k_df_axpy_mrhs(
    int const    n,
    int const    nrhs,
    int const    ld,
    float const  s,
    float const *ah,
    float const *al,
    float const *xh,
    float const *xl,
    float       *yh,
    float       *yl) {

    int const i = blockIdx.x * blockDim.x + threadIdx.x;
    int const c = blockIdx.y;
    if (i >= n || c >= nrhs)
        return;
    std::size_t const o = static_cast<std::size_t>(c) * ld + i;
    df32 const a = df_mul(df_make(ah[c], al[c]), df_make(s, 0.f));
    df32 const r = df_add_acc(df_make(yh[o], yl[o]),
                              df_mul(a, df_make(xh[o], xl[o])));
    yh[o] = r.hi;
    yl[o] = r.lo;
}

/*  v = x / a[col], with a zero-ish divisor left as an exact zero vector:
    that is a happy breakdown, and the least squares below is told how
    many columns are real via `keff`. */
__global__ void k_df_normalize_mrhs(
    int const    n,
    int const    nrhs,
    int const    ld,
    int const    step,
    float const *nh,
    float const *nl,
    float const *bh,
    float       *xh,
    float       *xl,
    int         *keff) {

    int const i = blockIdx.x * blockDim.x + threadIdx.x;
    int const c = blockIdx.y;
    if (i >= n || c >= nrhs)
        return;
    std::size_t const o = static_cast<std::size_t>(c) * ld + i;

    float const nrm = nh[c];
    if (!(nrm > 1e-14f * bh[c])) {
        xh[o] = 0.f;
        xl[o] = 0.f;
        if (i == 0)
            atomicMin(&keff[c], step);
        return;
    }
    df32 const r = df_div(df_make(xh[o], xl[o]), df_make(nh[c], nl[c]));
    xh[o] = r.hi;
    xl[o] = r.lo;
}

/*  Least squares min || H y - beta e1 || by Givens, one thread per
    column. H is (j+1) x j, stored column major per right-hand side. */
__global__ void k_gmres_lsq(
    int const    j,
    int const    nrhs,
    float const *hh,
    float const *hl,
    float const *bh,
    float const *bl,
    int const   *keff,
    float       *yh,
    float       *yl) {

    int const c = blockIdx.x * blockDim.x + threadIdx.x;
    if (c >= nrhs)
        return;

    int const k = (keff[c] < j)? keff[c] : j;
    std::size_t const hb = static_cast<std::size_t>(c) * (j + 1) * j;

    df32 r[9][8];                 /* (j+1) x j, j <= 8 */
    df32 g[9];
    for (int a = 0; a <= k; ++a) {
        g[a] = df_make(0.f, 0.f);
        for (int b = 0; b < k; ++b)
            r[a][b] = df_make(hh[hb + static_cast<std::size_t>(b) * (j + 1) + a],
                              hl[hb + static_cast<std::size_t>(b) * (j + 1) + a]);
    }
    g[0] = df_make(bh[c], bl[c]);

    for (int b = 0; b < k; ++b) {
        df32 const a1 = r[b][b], a2 = r[b + 1][b];
        df32 const d = df_sqrt(df_add_acc(df_mul(a1, a1), df_mul(a2, a2)));
        if (!(d.hi > 0.f))
            continue;
        df32 const cs = df_div(a1, d), sn = df_div(a2, d);
        for (int q = b; q < k; ++q) {
            df32 const t1 = r[b][q], t2 = r[b + 1][q];
            r[b][q]     = df_add_acc(df_mul(cs, t1), df_mul(sn, t2));
            r[b + 1][q] = df_sub_acc(df_mul(cs, t2), df_mul(sn, t1));
        }
        df32 const t1 = g[b], t2 = g[b + 1];
        g[b]     = df_add_acc(df_mul(cs, t1), df_mul(sn, t2));
        g[b + 1] = df_sub_acc(df_mul(cs, t2), df_mul(sn, t1));
    }

    for (int b = k - 1; b >= 0; --b) {
        df32 acc = g[b];
        for (int q = b + 1; q < k; ++q)
            acc = df_sub_acc(acc, df_mul(r[b][q],
                                         df_make(yh[static_cast<std::size_t>(c) * j + q],
                                                 yl[static_cast<std::size_t>(c) * j + q])));
        df32 const v = (r[b][b].hi != 0.f)? df_div(acc, r[b][b])
                                          : df_make(0.f, 0.f);
        yh[static_cast<std::size_t>(c) * j + b] = v.hi;
        yl[static_cast<std::size_t>(c) * j + b] = v.lo;
    }
    for (int b = k; b < j; ++b) {
        yh[static_cast<std::size_t>(c) * j + b] = 0.f;
        yl[static_cast<std::size_t>(c) * j + b] = 0.f;
    }
}

/*  Scatter one column of H, produced as a per-column dot, into the
    Hessenberg store, accumulating (MGS with reorthogonalization adds to
    the same entry twice). */
__global__ void k_h_accum(
    int const    nrhs,
    int const    j,
    int const    row,
    int const    col,
    float const *vh,
    float const *vl,
    float       *hh,
    float       *hl) {

    int const c = blockIdx.x * blockDim.x + threadIdx.x;
    if (c >= nrhs)
        return;
    std::size_t const o = static_cast<std::size_t>(c) * (j + 1) * j
                        + static_cast<std::size_t>(col) * (j + 1) + row;
    df32 const r = df_add_acc(df_make(hh[o], hl[o]),
                              df_make(vh[c], vl[c]));
    hh[o] = r.hi;
    hl[o] = r.lo;
}

/*  DF32 matvec over k columns: one warp per (row, right-hand side), with
    consecutive warps on the same row so the row of A is fetched once and
    serves all k -- the same amortization the batched TRSV uses. */
__global__ void k_df_matvec_mrhs(
    int const    n,
    int const    nrhs,
    int const    ld,
    float const *ah,
    float const *al,
    float const *xh,
    float const *xl,
    float       *yh,
    float       *yl) {

    int const gw   = (blockIdx.x * blockDim.x + threadIdx.x) >> 5;
    int const lane = threadIdx.x & 31;
    if (gw >= n * nrhs)
        return;
    int const r = gw / nrhs;
    std::size_t const off = static_cast<std::size_t>(gw % nrhs) * ld;

    df32 acc = df_make(0.f, 0.f);
    for (int q = lane; q < n; q += 32)
        acc = df_add_acc(acc, df_mul(
            df_make(ah[static_cast<std::size_t>(r) * n + q],
                    al[static_cast<std::size_t>(r) * n + q]),
            df_make(xh[off + q], xl[off + q])));
    for (int o = 16; o > 0; o >>= 1) {
        float const oh = __shfl_down_sync(0xffffffffu, acc.hi, o);
        float const ol = __shfl_down_sync(0xffffffffu, acc.lo, o);
        acc = df_add_acc(acc, df_make(oh, ol));
    }
    if (lane == 0) {
        yh[off + r] = acc.hi;
        yl[off + r] = acc.lo;
    }
}

/*  ---- slice-cascade saturation on the production carrier -------------

    i_sat is the level at which the DF32 accumulator stops changing BITS.
    Not a chi criterion, not a residual threshold: the thing itself.

    This replicates k_slice_rows exactly -- per-row max over |hi|, scale
    max/127, rintf, clamp to +-127, exact two_prod, and the residual
    updated with df_sub_acc -- and adds a change detector on the
    accumulator. Replicating rather than calling it is deliberate: the
    vendored kernel writes slices and scales and keeps no accumulator,
    and the numerics here are line-for-line the same.

    The carrier has to govern the WHOLE cascade, residual included. The
    simulation measured what happens otherwise: with the slicer left in
    fp64 and only the accumulator widened, i_sat ran past 24 levels
    against a predicted 17, because the contributions floored at
    u * rowmax instead of continuing to shrink geometrically. Here the
    residual is DF32 because the arm's residual is DF32.

    The segment width is the panel's 256-column k-extent, because that is
    the extent the trailing update actually slices over. Saturation
    depends on the dynamic range the scale has to cover, so measuring it
    over a different extent would measure a different quantity. */
__global__ void k_saturation(
    int const    n,
    int const    c0,
    int const    width,
    int const    max_depth,
    int const    qmax,          /* beta = 2*qmax: 7 -> 14, 31 -> 62, 127 -> 254 */
    float const *ah,
    float const *al,
    int         *last_change,
    int         *uf_level,
    float       *g_ratio,
    int         *isat_i0,       /* optional, QLU_I0MAX x n */
    float       *scale_out) {   /* optional, depth x n */

    /*  Sized for the only launch configuration this kernel has, 256
        threads; the reductions below read blockDim.x so they stay
        correct if that changes, but these arrays would not. */
    __shared__ float rh[256], rl[256], acch[256], accl[256], red[256];
    __shared__ float gmx[256];
    __shared__ int   any;

    /*  cor:absorbgeo reads Gamma = max_{(r,s) in I} C_rs / m_rs, where
        |delta^(i)_rs| <= C_rs beta^-i and m_rs is a floor on |a^(i)_rs|
        holding for ALL i >= i_0. Two things follow that the first
        version of this kernel got wrong.

        First, the ratio pairs the largest contribution with the SMALLEST
        accumulator over the tail, not with the accumulator that happened
        to be there at the same level. Dividing by the running |a^(i-1)|
        gives max_i (C_i / a_{i-1}), which is bounded above by
        (max_i C_i) / (min_i a_i) and equals it only when the accumulator
        never shrinks. So the old reading under-estimates Gamma wherever
        the accumulator cancels later -- the direction that leaves rows
        above i*.

        Second, i_0 is part of the statement and is measured, not
        assumed: the index set is entries that stay nonzero from i_0 on,
        so an entry that revives after a zero is outside I for small i_0
        and inside it for larger. Sweeping i_0 is what the core's remark
        means by the startup index being operational -- the within-family
        trends collapse once it is taken from the data. */
    float cmax[QLU_I0MAX], mmin[QLU_I0MAX];
    bool  live[QLU_I0MAX];
    for (int k = 0; k != QLU_I0MAX; ++k) {
        cmax[k] = -1e30f;
        mmin[k] =  1e30f;
        live[k] = true;
    }

    int const i = blockIdx.x;
    int const t = threadIdx.x;

    float const v_h = (t < width)? ah[static_cast<std::size_t>(i) * n + c0 + t] : 0.f;
    float const v_l = (t < width)? al[static_cast<std::size_t>(i) * n + c0 + t] : 0.f;
    rh[t] = v_h;
    rl[t] = v_l;
    acch[t] = 0.f;
    accl[t] = 0.f;
    gmx[t]  = -1e30f;
    int last = 0;
    int uf   = 0;
    /*  Per-ENTRY last change. `last` below is the row-level OR, which is
        what i_sat has always meant here; this is the finer quantity the
        corollary needs, because the index set I excludes entries rather
        than rows. */
    int last_e = 0;

    /*  And the level at which lem:absorb's own criterion last failed.

        These are different quantities and conflating them is what made
        eps_sat read 11.9. `last_e` is bit-identity of the DF32 PAIR,
        which is what i_sat has always meant here and is the right
        thing for the depth dial: it answers "does another slice change
        the stored value". But lem:absorb is stated for "a
        fixed-precision binary carrier with unit roundoff u_c, with
        underflow and subnormals excluded", and an unevaluated
        two-float pair is not one. Its low word can absorb increments
        far below (u_c/2)|a| without the pair being bit-identical, so
        the pair keeps recording changes for levels after a genuine
        49-bit carrier would have stopped -- 18 rather than 8 on the
        worst U12 entries.

        cor:absorbgeo bounds the lemma's depth, so the lemma's
        criterion is what it has to be measured against:
        fl(a + delta) = a once |delta| < rad_c(a), and
        rad_c(a) >= (u_c/2)|a| is the carrier-independent sufficient
        form the lemma gives. */
    int last_abs = 0;

    /*  The radix is a parameter because the core registers the carrier
        translation law across beta in {14, 62, 254}, and a single radix
        tests one point of that sweep. beta = 2*qmax: the slice is
        rounded to +-qmax, so one level buys a factor of 2*qmax. */
    float const fq    = static_cast<float>(qmax);
    float const lbeta = __logf(2.f * fq);
    __syncthreads();

    for (int s = 1; s <= max_depth; ++s) {

        float m = (t < width)? fabsf(rh[t]) : 0.f;
        red[t] = m;
        __syncthreads();
        for (int o = blockDim.x >> 1; o > 0; o >>= 1) {
            if (t < o)
                red[t] = fmaxf(red[t], red[t + o]);
            __syncthreads();
        }

        float sc = (red[0] > 0.f)? red[0] / fq : 1.f;
        /*  The residual reaches the denormal floor and the scale flushes
            to zero long before a fixed depth cap is hit; the division
            would then poison the whole cascade with inf. Guarded, and
            the fact that it happened is REPORTED rather than swallowed,
            because a run that underflowed is measuring the exponent
            range and not the saturation depth. */
        /*  The residual has reached the denormal floor: there is nothing
            left to slice, and the division would poison the cascade with
            inf. Record WHEN it happened per row rather than raising one
            global flag -- a row whose residual vanished has saturated,
            and only underflow BEFORE the last change invalidates the
            measurement. The first version flagged the whole grid on any
            row underflowing and reported nothing usable. */
        if (sc == 0.f) {
            sc = 1.f;
            if (uf == 0)
                uf = s;
        }

        if (t == 0) {
            any = 0;
            if (scale_out != nullptr)
                scale_out[static_cast<std::size_t>(s - 1) * gridDim.x + i]
                    = sc;
        }
        __syncthreads();

        if (t < width) {
            float q = rintf(rh[t] / sc);
            q = fminf(fmaxf(q, -fq), fq);
            df32 const x    = two_prod(sc, q);
            df32 const prev = df_make(acch[t], accl[t]);
            df32 const a    = df_add_acc(prev, x);
            if (a.hi != prev.hi || a.lo != prev.lo) {
                atomicOr(&any, 1);
                last_e = s;
            }
            /*  U_C/2 = 2^-50. Against the PRE-update magnitude, which
                is the `a` of the lemma's fl(a + delta). */
            float const pv_abs = fabsf(prev.hi + prev.lo);
            if (fabsf(x.hi + x.lo) >= 0x1p-50f * pv_abs)
                last_abs = s;

            /*  Kept in LOG space throughout. Forming the ratio times
                beta^i and taking the log afterwards overflows fp32 at
                i = 16 -- beta^16 is 1e38 -- and reports inf for every
                cell, which is what the first version did. */
            float const av = fabsf(a.hi + a.lo);
            float const xv = fabsf(x.hi + x.lo);
            float const lx = (xv > 0.f)? __logf(xv) / lbeta : -1e30f;
            float const la = (av > 0.f)? __logf(av) / lbeta :  1e30f;

            for (int k = 0; k != QLU_I0MAX; ++k) {
                if (s < k + 1)
                    continue;
                if (av <= 0.f) {
                    /*  m_rs > 0 is a hypothesis of the corollary, so an
                        entry that is zero anywhere from i_0 on is simply
                        not in I at that i_0. */
                    live[k] = false;
                    continue;
                }
                if (xv > 0.f)
                    cmax[k] = fmaxf(cmax[k], lx + (float)s);
                mmin[k] = fminf(mmin[k], la);
            }

            acch[t] = a.hi;
            accl[t] = a.lo;
            df32 const r = df_sub_acc(df_make(rh[t], rl[t]), x);
            rh[t] = r.hi;
            rl[t] = r.lo;
        }
        __syncthreads();

        if (any != 0)
            last = s;
    }

    /*  Row maxima of the Gamma reading, one per candidate i_0. The max
        over entries of (cmax - mmin) is taken per entry first: the max
        of a difference is not the difference of the extremes. */
    for (int k = 0; k != QLU_I0MAX; ++k) {
        __syncthreads();
        gmx[t] = (t < width && live[k] && cmax[k] > -1e29f)?
                     cmax[k] - mmin[k] : -1e30f;
        __syncthreads();
        for (int o = blockDim.x >> 1; o > 0; o >>= 1) {
            if (t < o)
                gmx[t] = fmaxf(gmx[t], gmx[t + o]);
            __syncthreads();
        }
        if (t == 0)
            g_ratio[static_cast<std::size_t>(k) * gridDim.x + i] = gmx[0];

        /*  i_sat over the SAME index set that produced g(i_0).

            Reduced as the max of the PER-ENTRY slack, not as a max of
            i_sat to be differenced against a max of g afterwards. Those
            are maxima over different entries, and subtracting them is
            not a bound on anything: it read 9.8 for U12 while the
            block's g was 3, which is arithmetically impossible for a
            single entry and was an artifact of the pairing. The
            corollary is a per-entry statement, so the slack is formed
            per entry and the worst one is what gets reported. */
        if (isat_i0 != nullptr) {
            __syncthreads();
            bool const in_I = (t < width && live[k] && cmax[k] > -1e29f);
            red[t] = in_I? static_cast<float>(last_e) : -1.f;
            __syncthreads();
            for (int o = blockDim.x >> 1; o > 0; o >>= 1) {
                if (t < o)
                    red[t] = fmaxf(red[t], red[t + o]);
                __syncthreads();
            }
            if (t == 0)
                isat_i0[static_cast<std::size_t>(k) * gridDim.x + i] =
                    (red[0] < 0.f)? -1 : static_cast<int>(red[0]) + 1;

            /*  eps_entry = i_sat_entry - g_entry - log_beta(1/u_c),
                stashed in the upper half of g_ratio. */
            __syncthreads();
            gmx[t] = in_I? (static_cast<float>(last_abs + 1)
                            - (cmax[k] - mmin[k])
                            - (49.f * 0.693147f / lbeta)) : -1e30f;
            __syncthreads();
            for (int o = blockDim.x >> 1; o > 0; o >>= 1) {
                if (t < o)
                    gmx[t] = fmaxf(gmx[t], gmx[t + o]);
                __syncthreads();
            }
            if (t == 0)
                g_ratio[static_cast<std::size_t>(QLU_I0MAX + k) * gridDim.x + i]
                    = gmx[0];
        }
    }

    if (t == 0) {
        last_change[i] = last;
        uf_level[i]    = uf;
    }
}

/*  ---- multi-RHS triangular solve -------------------------------------

    The solve was a loop over columns: k right-hand sides cost k
    independent chains and the measured per-RHS time was flat at 19.35 ms
    from k=1 to k=16, i.e. no amortization at all. The phase split at k=16
    says where it all is -- TRSV 97.5 percent, residual 2.0, gather 0.2,
    update 0.3 -- so these two kernel pairs are the whole job and the
    residual stays per column.

    Each column's arithmetic is UNCHANGED: same loop bounds, same warp
    reduction order, same sub-block sequence. The batched path is
    therefore bit-identical to the column loop, which is what the gate
    checks. The win is not arithmetic, it is that one pass over L\U now
    serves k columns and that the diagonal apply, which ran in a SINGLE
    block, now runs in k.

    Vectors are n x nrhs, column major with stride ldv, so a single-vector
    kernel still works on any one column by pointer offset. */

/*  Off-diagonal update, one warp per (row, rhs). Consecutive warps take
    the same row across right-hand sides, so the row of L\U is fetched
    once and serves all of them. */
__global__ void k_trsv_off_L_mrhs(
    int const    n,
    int const    i0,
    int const    ni,
    int const    nrhs,
    int const    ldv,
    float const *luh,
    float const *lul,
    float const *yh,
    float const *yl,
    float const *bh,
    float const *bl,
    float       *rh,
    float       *rl) {

    int const gw   = (blockIdx.x * blockDim.x + threadIdx.x) >> 5;
    int const lane = threadIdx.x & 31;
    if (gw >= ni * nrhs)
        return;
    int const r = i0 + gw / nrhs;
    std::size_t const off = static_cast<std::size_t>(gw % nrhs) * ldv;

    df32 acc = df_make(0.f, 0.f);
    for (int j = lane; j < i0; j += 32)
        acc = df_add_acc(acc, df_mul(
            df_make(luh[static_cast<std::size_t>(r) * n + j],
                    lul[static_cast<std::size_t>(r) * n + j]),
            df_make(yh[off + j], yl[off + j])));
    for (int o = 16; o > 0; o >>= 1) {
        float const oh = __shfl_down_sync(0xffffffffu, acc.hi, o);
        float const ol = __shfl_down_sync(0xffffffffu, acc.lo, o);
        acc = df_add_acc(acc, df_make(oh, ol));
    }
    if (lane == 0) {
        df32 const v = df_sub_acc(df_make(bh[off + r], bl[off + r]), acc);
        rh[off + r] = v.hi;
        rl[off + r] = v.lo;
    }
}

__global__ void k_trsv_off_U_mrhs(
    int const    n,
    int const    i0,
    int const    ni,
    int const    nrhs,
    int const    ldv,
    float const *luh,
    float const *lul,
    float const *yh,
    float const *yl,
    float const *bh,
    float const *bl,
    float       *rh,
    float       *rl) {

    int const gw   = (blockIdx.x * blockDim.x + threadIdx.x) >> 5;
    int const lane = threadIdx.x & 31;
    if (gw >= ni * nrhs)
        return;
    int const r = i0 + gw / nrhs;
    std::size_t const off = static_cast<std::size_t>(gw % nrhs) * ldv;

    df32 acc = df_make(0.f, 0.f);
    for (int j = i0 + ni + lane; j < n; j += 32)
        acc = df_add_acc(acc, df_mul(
            df_make(luh[static_cast<std::size_t>(r) * n + j],
                    lul[static_cast<std::size_t>(r) * n + j]),
            df_make(yh[off + j], yl[off + j])));
    for (int o = 16; o > 0; o >>= 1) {
        float const oh = __shfl_down_sync(0xffffffffu, acc.hi, o);
        float const ol = __shfl_down_sync(0xffffffffu, acc.lo, o);
        acc = df_add_acc(acc, df_make(oh, ol));
    }
    if (lane == 0) {
        df32 const v = df_sub_acc(df_make(bh[off + r], bl[off + r]), acc);
        rh[off + r] = v.hi;
        rl[off + r] = v.lo;
    }
}

/*  Diagonal apply, one BLOCK per right-hand side. The single-RHS kernel
    launches one block on a 132-SM device; this is the same body with the
    vectors offset, so k right-hand sides fill k blocks. */
__global__ void k_diag_apply_L_mrhs(
    int const    n,
    int const    i0,
    int const    ni,
    int const    ib,
    int const    ldv,
    float const *luh,
    float const *lul,
    float const *dh,
    float const *dl,
    float const *rh,
    float const *rl,
    float       *yh,
    float       *yl) {

    __shared__ float ys[256], yls[256], rrh[256], rrl[256];
    int const t = threadIdx.x;
    std::size_t const off = static_cast<std::size_t>(blockIdx.x) * ldv;

    for (int sb = 0; sb < ni; sb += ib) {
        int const sw = (ni - sb < ib)? (ni - sb) : ib;
        if (t < sw) {
            df32 rr = df_make(rh[off + i0 + sb + t], rl[off + i0 + sb + t]);
            for (int j = 0; j < sb; ++j)
                rr = df_sub_acc(rr, df_mul(
                    df_make(luh[static_cast<std::size_t>(i0 + sb + t) * n + (i0 + j)],
                            lul[static_cast<std::size_t>(i0 + sb + t) * n + (i0 + j)]),
                    df_make(ys[j], yls[j])));
            rrh[t] = rr.hi;
            rrl[t] = rr.lo;
        }
        __syncthreads();
        if (t < sw) {
            float const *mh = dh + static_cast<std::size_t>((i0 + sb) / ib) * ib * ib;
            float const *ml = dl + static_cast<std::size_t>((i0 + sb) / ib) * ib * ib;
            df32 acc = df_make(0.f, 0.f);
            for (int q = 0; q < sw; ++q)
                acc = df_add_acc(acc, df_mul(df_make(mh[t * ib + q], ml[t * ib + q]),
                                             df_make(rrh[q], rrl[q])));
            ys[sb + t]  = acc.hi;
            yls[sb + t] = acc.lo;
        }
        __syncthreads();
    }
    for (int m = t; m < ni; m += blockDim.x) {
        yh[off + i0 + m] = ys[m];
        yl[off + i0 + m] = yls[m];
    }
}

__global__ void k_diag_apply_U_mrhs(
    int const    n,
    int const    i0,
    int const    ni,
    int const    ib,
    int const    ldv,
    float const *luh,
    float const *lul,
    float const *dh,
    float const *dl,
    float const *rh,
    float const *rl,
    float       *yh,
    float       *yl) {

    __shared__ float ys[256], yls[256], rrh[256], rrl[256];
    int const t = threadIdx.x;
    std::size_t const off = static_cast<std::size_t>(blockIdx.x) * ldv;

    for (int sb = ((ni - 1) / ib) * ib; sb >= 0; sb -= ib) {
        int const sw = (sb + ib <= ni)? ib : (ni - sb);
        if (t < sw) {
            df32 rr = df_make(rh[off + i0 + sb + t], rl[off + i0 + sb + t]);
            for (int j = sb + sw; j < ni; ++j)
                rr = df_sub_acc(rr, df_mul(
                    df_make(luh[static_cast<std::size_t>(i0 + sb + t) * n + (i0 + j)],
                            lul[static_cast<std::size_t>(i0 + sb + t) * n + (i0 + j)]),
                    df_make(ys[j], yls[j])));
            rrh[t] = rr.hi;
            rrl[t] = rr.lo;
        }
        __syncthreads();
        if (t < sw) {
            float const *mh = dh + static_cast<std::size_t>((i0 + sb) / ib) * ib * ib;
            float const *ml = dl + static_cast<std::size_t>((i0 + sb) / ib) * ib * ib;
            df32 acc = df_make(0.f, 0.f);
            for (int q = 0; q < sw; ++q)
                acc = df_add_acc(acc, df_mul(df_make(mh[t * ib + q], ml[t * ib + q]),
                                             df_make(rrh[q], rrl[q])));
            ys[sb + t]  = acc.hi;
            yls[sb + t] = acc.lo;
        }
        __syncthreads();
    }
    for (int m = t; m < ni; m += blockDim.x) {
        yh[off + i0 + m] = ys[m];
        yl[off + i0 + m] = yls[m];
    }
}

/*  The blocked drivers, batched. Same block sequence as the vendored
    single-vector ones, so each column sees the identical order. */
void trsv_L_mrhs(
    int const n, int const blk, int const ib, int const nrhs, int const ldv,
    float const *luh, float const *lul, float const *dlh, float const *dll,
    float const *bh, float const *bl, float *yh, float *yl,
    float *rh, float *rl) {

    for (int i0 = 0; i0 < n; i0 += blk) {
        int const ni = (i0 + blk <= n)? blk : (n - i0);
        int const w  = ni * nrhs * 32;
        k_trsv_off_L_mrhs<<<(w + 255) / 256, 256>>>(
            n, i0, ni, nrhs, ldv, luh, lul, yh, yl, bh, bl, rh, rl);
        KERNEL_CHECK();
        k_diag_apply_L_mrhs<<<nrhs, 256>>>(
            n, i0, ni, ib, ldv, luh, lul, dlh, dll, rh, rl, yh, yl);
        KERNEL_CHECK();
    }
}

void trsv_U_mrhs(
    int const n, int const blk, int const ib, int const nrhs, int const ldv,
    float const *luh, float const *lul, float const *duh, float const *dul,
    float const *bh, float const *bl, float *yh, float *yl,
    float *rh, float *rl) {

    for (int i0 = ((n - 1) / blk) * blk; i0 >= 0; i0 -= blk) {
        int const ni = (i0 + blk <= n)? blk : (n - i0);
        int const w  = ni * nrhs * 32;
        k_trsv_off_U_mrhs<<<(w + 255) / 256, 256>>>(
            n, i0, ni, nrhs, ldv, luh, lul, yh, yl, bh, bl, rh, rl);
        KERNEL_CHECK();
        k_diag_apply_U_mrhs<<<nrhs, 256>>>(
            n, i0, ni, ib, ldv, luh, lul, duh, dul, rh, rl, yh, yl);
        KERNEL_CHECK();
    }
}

/*  One application of the left preconditioner B0^-1 = U^-1 L^-1 P to k
    columns: exactly what the stationary path does per step, reused so
    the two solvers share a preconditioner rather than each having one. */
void apply_precond(
    state *s, int const n, int const nrhs, int const ld,
    float *inh, float *inl,          /* consumed, gathered in place */
    float *outh, float *outl,
    float *t1h, float *t1l) {

    int const T = launch::BLOCK_SIZE;
    int const g = (n + T - 1) / T;
    for (int c = 0; c != nrhs; ++c)
        LAUNCH((gather_kernel<<<g, T>>>(
            n, s->d_perm, inh + static_cast<std::size_t>(c) * ld,
            inl + static_cast<std::size_t>(c) * ld,
            outh + static_cast<std::size_t>(c) * ld,
            outl + static_cast<std::size_t>(c) * ld)));

    if (s->srung_ib != 0) {
        trsv_L_mrhs(n, 256, s->srung_ib, nrhs, ld, s->d_hi, s->d_lo,
                    s->d_dlh, s->d_dll, outh, outl, t1h, t1l,
                    s->d_th, s->d_tl);
        trsv_U_mrhs(n, 256, s->srung_ib, nrhs, ld, s->d_hi, s->d_lo,
                    s->d_duh, s->d_dul, t1h, t1l, outh, outl,
                    s->d_th, s->d_tl);
    } else {
        for (int c = 0; c != nrhs; ++c) {
            std::size_t const o = static_cast<std::size_t>(c) * ld;
            trsv_L_blocked(n, 256, s->d_hi, s->d_lo, outh + o, outl + o,
                           t1h + o, t1l + o, s->d_th, s->d_tl);
            trsv_U_blocked(n, 256, s->d_hi, s->d_lo, t1h + o, t1l + o,
                           outh + o, outl + o, s->d_th, s->d_tl);
        }
    }
}

/*  Workspace for GMRES-IR(j) on k columns. */
bool ensure_gmres(state *s, int const j, std::size_t const k) {

    if (s->gm_j == j && s->gm_k == k)
        return true;

    std::size_t const nk = s->n * k;
    struct { float **p; std::size_t n; } const want[] = {
        {&s->gm_vh, static_cast<std::size_t>(j + 1) * nk},
        {&s->gm_vl, static_cast<std::size_t>(j + 1) * nk},
        {&s->gm_wh, nk}, {&s->gm_wl, nk},
        {&s->gm_th, nk}, {&s->gm_tl, nk},
        {&s->gm_uh, nk}, {&s->gm_ul, nk},
        {&s->gm_hh, k * static_cast<std::size_t>(j + 1) * j},
        {&s->gm_hl, k * static_cast<std::size_t>(j + 1) * j},
        {&s->gm_yh, k * static_cast<std::size_t>(j)},
        {&s->gm_yl, k * static_cast<std::size_t>(j)},
        {&s->gm_sh, k}, {&s->gm_sl, k},
        {&s->gm_bh, k}, {&s->gm_bl, k},
    };
    for (auto const &w : want) {
        void *p = s->acquire(w.n * sizeof(float));
        if (p == nullptr)
            return false;
        *w.p = static_cast<float *>(p);
    }
    void *p = s->acquire(k * sizeof(int));
    if (p == nullptr)
        return false;
    s->gm_keff = static_cast<int *>(p);

    s->gm_j = j;
    s->gm_k = k;
    return true;
}

/*  j Arnoldi steps on Op(v) = B0^-1 (A v), starting from the normalized
    B0^-1 r, then the least squares and the update. One outer step.

    Modified Gram-Schmidt with ONE REORTHOGONALIZATION PASS, which the
    reference keeps because I + M can be severely nonnormal; dropping it
    is not a simplification, it is a different algorithm. */
void gmres_inner(
    state *s, int const n, int const nrhs, int const ld, int const j,
    float *rh, float *rl,          /* the residual, consumed */
    float *xh, float *xl) {        /* updated in place */

    int const T = launch::BLOCK_SIZE;
    int const g = (n + T - 1) / T;
    dim3 const gv((n + T - 1) / T, nrhs);
    int const gc = (nrhs + 255) / 256;
    std::size_t const nk = static_cast<std::size_t>(n) * nrhs;

    CUDA_CHECK(cudaMemset(s->gm_hh, 0,
        static_cast<std::size_t>(nrhs) * (j + 1) * j * sizeof(float)));
    CUDA_CHECK(cudaMemset(s->gm_hl, 0,
        static_cast<std::size_t>(nrhs) * (j + 1) * j * sizeof(float)));
    std::vector<int> const kf(nrhs, j);
    CUDA_CHECK(cudaMemcpy(s->gm_keff, kf.data(), nrhs * sizeof(int),
                          cudaMemcpyHostToDevice));

    /*  V_0 = B0^-1 r / || B0^-1 r ||. */
    apply_precond(s, n, nrhs, ld, rh, rl, s->gm_vh, s->gm_vl,
                  s->gm_th, s->gm_tl);
    k_df_dot_mrhs<<<nrhs, 256>>>(n, ld, s->gm_vh, s->gm_vl,
                                 s->gm_vh, s->gm_vl, s->gm_sh, s->gm_sl);
    KERNEL_CHECK();
    k_df_sqrt_scalars<<<gc, 256>>>(nrhs, s->gm_sh, s->gm_sl,
                                   s->gm_bh, s->gm_bl);
    KERNEL_CHECK();
    k_df_normalize_mrhs<<<gv, T>>>(n, nrhs, ld, 0, s->gm_bh, s->gm_bl,
                                   s->gm_bh, s->gm_vh, s->gm_vl,
                                   s->gm_keff);
    KERNEL_CHECK();

    for (int i = 0; i != j; ++i) {

        float *vi_h = s->gm_vh + static_cast<std::size_t>(i) * nk;
        float *vi_l = s->gm_vl + static_cast<std::size_t>(i) * nk;

        /*  w = B0^-1 (A v_i). */
        k_df_matvec_mrhs<<<(n * nrhs * 32 + 255) / 256, 256>>>(
            n, nrhs, ld, s->d_ah, s->d_al, vi_h, vi_l,
            s->gm_th, s->gm_tl);
        KERNEL_CHECK();
        /*  The triangular solve's intermediate is an n x k vector, not
            a per-column scalar. Passing gm_y here -- which is k*j --
            overran it by a factor of n/j and produced a backward error
            of 1e-2 rather than a crash. */
        apply_precond(s, n, nrhs, ld, s->gm_th, s->gm_tl,
                      s->gm_wh, s->gm_wl, s->gm_uh, s->gm_ul);

        for (int pass = 0; pass != 2; ++pass)
            for (int l = 0; l <= i; ++l) {
                float *vl_h = s->gm_vh + static_cast<std::size_t>(l) * nk;
                float *vl_l = s->gm_vl + static_cast<std::size_t>(l) * nk;
                k_df_dot_mrhs<<<nrhs, 256>>>(n, ld, vl_h, vl_l,
                                             s->gm_wh, s->gm_wl,
                                             s->gm_sh, s->gm_sl);
                KERNEL_CHECK();
                k_h_accum<<<gc, 256>>>(nrhs, j, l, i, s->gm_sh, s->gm_sl,
                                       s->gm_hh, s->gm_hl);
                KERNEL_CHECK();
                k_df_axpy_mrhs<<<gv, T>>>(n, nrhs, ld, -1.f,
                                          s->gm_sh, s->gm_sl, vl_h, vl_l,
                                          s->gm_wh, s->gm_wl);
                KERNEL_CHECK();
            }

        k_df_dot_mrhs<<<nrhs, 256>>>(n, ld, s->gm_wh, s->gm_wl,
                                     s->gm_wh, s->gm_wl,
                                     s->gm_sh, s->gm_sl);
        KERNEL_CHECK();
        k_df_sqrt_scalars<<<gc, 256>>>(nrhs, s->gm_sh, s->gm_sl,
                                       s->gm_sh, s->gm_sl);
        KERNEL_CHECK();
        k_h_accum<<<gc, 256>>>(nrhs, j, i + 1, i, s->gm_sh, s->gm_sl,
                               s->gm_hh, s->gm_hl);
        KERNEL_CHECK();

        if (i + 1 == j)
            break;
        float *vn_h = s->gm_vh + static_cast<std::size_t>(i + 1) * nk;
        float *vn_l = s->gm_vl + static_cast<std::size_t>(i + 1) * nk;
        CUDA_CHECK(cudaMemcpy(vn_h, s->gm_wh, nk * sizeof(float),
                              cudaMemcpyDeviceToDevice));
        CUDA_CHECK(cudaMemcpy(vn_l, s->gm_wl, nk * sizeof(float),
                              cudaMemcpyDeviceToDevice));
        k_df_normalize_mrhs<<<gv, T>>>(n, nrhs, ld, i + 1,
                                       s->gm_sh, s->gm_sl, s->gm_bh,
                                       vn_h, vn_l, s->gm_keff);
        KERNEL_CHECK();
    }

    k_gmres_lsq<<<gc, 256>>>(j, nrhs, s->gm_hh, s->gm_hl,
                             s->gm_bh, s->gm_bl, s->gm_keff,
                             s->gm_yh, s->gm_yl);
    KERNEL_CHECK();

    /*  x += sum_i y_i V_i. */
    for (int i = 0; i != j; ++i) {
        float *vi_h = s->gm_vh + static_cast<std::size_t>(i) * nk;
        float *vi_l = s->gm_vl + static_cast<std::size_t>(i) * nk;
        k_df_axpy_strided<<<gv, T>>>(n, nrhs, ld, j, i,
                                     s->gm_yh, s->gm_yl, vi_h, vi_l,
                                     xh, xl);
        KERNEL_CHECK();
    }
    (void)g;
}

/*  Blocked right-looking LU with the Ozaki-II trailing update.

    The panel, the bulk row interchange and the U12 block solve are the
    vendored ones, called in the vendored order -- this is deliberately a
    copy of int8lu_factor's per-panel loop with one block replaced, so the
    two arms differ in the trailing update and in nothing else. Anything
    the sliced arm gets from its panel, this gets identically.

    What is NOT reproduced: the whole-factor CUDA graph, the async and
    persistent panels, the look-ahead and the FUSE backends. Those are
    built around the sliced update's schedule. The comparison this
    supports is against the per-panel sliced path.

    Returns false if a trailing update was rejected -- Ozaki-II has no
    meaning on a zero row of L21 or a zero column of U12, and a silent
    wrong answer there would be worse than a failed factorization. */
bool oii_factor(
    int const       n,
    int const       b,
    int const       kfac,
    float          *d_ah,
    float          *d_al,
    int            *d_piv,
    Int8LUScratch  &sc,
    oii::state     *os) {

#ifdef LPS_DUMP
    lps_lift_dump(n, -1, 0, kfac, kfac, d_ah, d_al, d_piv,
                  nullptr, nullptr, nullptr, nullptr);
#endif
    for (int p = 0; p < n; p += b) {

        int const bb = (p + b <= n)? b : (n - p);

        launch_panel_coop(n, p, bb, d_ah, d_al, d_piv + p, sc.gv, sc.gi);
        if (n - bb > 0)
            LAUNCH((k_laswp_bulk<<<(n - bb + 255) / 256, 256>>>(
                        n, p, bb, d_piv + p, d_ah, d_al)));

        /*  The last panel has no trailing update, but it still has a
            state worth recording: the injected hook in int8lu_factor
            fires at the END of the loop body and so catches it, and
            the two arms have to produce the same number of snapshots
            or the reader sees a shorter factorization than happened. */
        if (p + bb >= n) {
#ifdef LPS_DUMP
            lps_lift_dump(n, p, bb, kfac, kfac, d_ah, d_al, d_piv,
                          nullptr, nullptr, nullptr, nullptr);
#endif
            continue;
        }

        u12_blocked(n, p, bb, d_ah, d_al);

        int const mp = n - p - bb;
        int const np = mp;

        /*  L21 = carrier[p+bb : n, p : p+bb], U12 = carrier[p : p+bb,
            p+bb : n], both read in place at leading dimension n, and the
            product subtracted into the trailing block. No gather: that is
            what the strides are for. */
        std::size_t const l21 = static_cast<std::size_t>(p + bb) * n + p;
        std::size_t const u12 = static_cast<std::size_t>(p) * n + (p + bb);
        std::size_t const s22 = static_cast<std::size_t>(p + bb) * n
                              + (p + bb);

        if (!oii::gemm_df32(os, mp, np,
                            d_ah + l21, d_al + l21, n,
                            d_ah + u12, d_al + u12, n,
                            d_ah + s22, d_al + s22, n,
                            true)) {
            std::fprintf(stderr,
                         "[qlu/oii] trailing update rejected at panel "
                         "p=%d (mp=%d)\n", p, mp);
            return false;
        }
#ifdef LPS_DUMP
        /*  Same hook the injected one in int8lu_factor calls, so both
            arms produce the same dump format. Null slice pointers: the
            Ozaki-II update reads its operands out of the carrier and
            keeps no int8 slices, and the reader reconstructs L21 and
            U12 from the carrier anyway. */
        lps_lift_dump(n, p, bb, kfac, kfac, d_ah, d_al, d_piv,
                      nullptr, nullptr, nullptr, nullptr);
#endif
    }
    return true;
}

double factor(state *s) {

    if (s == nullptr)
        return 0.;

    timing::stopwatch watch;
    watch.start();

    if (s->which == kernel::oii) {
        if (!oii_factor(static_cast<int>(s->n), s->b, s->kfac,
                        s->d_hi, s->d_lo, s->d_piv, s->scratch,
                        s->oii_s))
            return -1.;
    } else {
        int8lu_factor(s->blas, static_cast<int>(s->n), s->b, s->kfac,
                      UPD_INT8, s->d_hi, s->d_lo, s->d_piv, s->scratch);
    }

    /*  The inverses depend only on the factor, so they are built here and
        reused by every refinement step of every right-hand side. Timed
        with the factorization because that is where the work is: charging
        them to the solve would flatter it. */
    if (s->srung_ib != 0)
        srung_invert(static_cast<int>(s->n), s->srung_ib,
                     s->d_hi, s->d_lo,
                     s->d_dlh, s->d_dll, s->d_duh, s->d_dul);

    double const ms = watch.stop();
    s->times.factor += ms;
    double const t_perm0 = ms;

    /*  Compose the sequential interchanges into a permutation. Serial by
        nature and n ints against an O(n^3) factorization, so the host does
        it; a device scan would buy nothing. Outside the timed region only
        because getrf's own pivot list is what it consumes. */
    std::size_t const n = s->n;
    std::vector<int> piv(n), perm(n);
    CUDA_CHECK(cudaMemcpy(piv.data(), s->d_piv, n * sizeof(int),
                          cudaMemcpyDeviceToHost));
    for (std::size_t i = 0; i != n; ++i)
        perm[i] = static_cast<int>(i);
    for (std::size_t k = 0; k != n; ++k) {
        int const j = piv[k];
        if (j >= 0 && static_cast<std::size_t>(j) < n)
            std::swap(perm[k], perm[static_cast<std::size_t>(j)]);
    }
    CUDA_CHECK(cudaMemcpy(s->d_perm, perm.data(), n * sizeof(int),
                          cudaMemcpyHostToDevice));

    /*  The compose is host-serial between two blocking copies, so the
        stopwatch's device timeline measures it fairly. */
    s->times.perm += watch.stop() - t_perm0;

    return ms;
}

/*  Grow the solve workspace to hold `k` columns. The triangular solve's
    scratch (d_th/d_tl) stays one vector wide only in the single-column
    path; the batched kernels write per column, so it grows too. */
bool ensure_rhs(state *s, std::size_t const k) {

    if (k <= s->rhs_cap)
        return true;

    /*  Growing keeps the previous buffers in `owned` until destroy
        rather than freeing them. Bounded by the number of DISTINCT k a
        state is asked for, which is one in every current caller; it is
        retention, not a leak. */

    float **const work[] = {&s->d_bh, &s->d_bl, &s->d_xh, &s->d_xl,
                            &s->d_rh, &s->d_rl, &s->d_yh, &s->d_yl,
                            &s->d_zh, &s->d_zl, &s->d_th, &s->d_tl};
    std::size_t const bytes = s->n * k * sizeof(float);
    for (std::size_t i = 0; i != sizeof work / sizeof *work; ++i) {
        void *p = s->acquire(bytes);
        if (p == nullptr)
            return false;
        *work[i] = static_cast<float *>(p);
    }
    s->rhs_cap = k;
    return true;
}

double solve(
    state        *s,
    double       *d_x,
    double const *d_b,
    std::size_t const k,
    std::size_t  *n_iterations,
    int const     inner_j) {

    if (s == nullptr)
        return 0.;
    if (inner_j < 0 || inner_j > 8) {
        std::fprintf(stderr, "[qlu] inner_j=%d out of range; the "
                             "least squares is sized for j <= 8\n",
                     inner_j);
        return 0.;
    }

    int const   n = static_cast<int>(s->n);
    int const   T = launch::BLOCK_SIZE;
    int const   g = (n + T - 1) / T;
    std::size_t used = 0;

    CUDA_CHECK(cudaDeviceSynchronize());
    s->n_marks = 0;
    s->mark(-1);

    timing::stopwatch outer;
    outer.start();

    /*  Grow the solve workspace to k columns, n x k column major so a
        single-vector kernel still works on one column by pointer offset.
        Allocated here and not in create() because create() does not know
        k; it happens once per distinct k, not per solve. */
    if (!ensure_rhs(s, k))
        return 0.;
    if (inner_j > 0 && !ensure_gmres(s, inner_j, k))
        return 0.;

    std::size_t const nk = s->n * k;
    std::size_t const ld = s->n;

    LAUNCH((k_split_f64<<<(int)((nk + T - 1) / T), T>>>(
        (int)nk, d_b, s->d_bh, s->d_bl)));
    CUDA_CHECK(cudaMemset(s->d_xh, 0, nk * sizeof(float)));
    CUDA_CHECK(cudaMemset(s->d_xl, 0, nk * sizeof(float)));

    /*  The batched pass runs every column, converged ones included, so
        it reads the correction vector of columns that never had a
        gather -- a column that meets its test on the first residual is
        exactly that case, and its slot would otherwise hold whatever
        cudaMalloc returned. The values are discarded either way, but a
        NaN read is not free and reading uninitialized memory is not
        something to leave in on the grounds that the answer survives. */
    CUDA_CHECK(cudaMemset(s->d_yh, 0, nk * sizeof(float)));
    CUDA_CHECK(cudaMemset(s->d_yl, 0, nk * sizeof(float)));
    CUDA_CHECK(cudaMemset(s->d_zh, 0, nk * sizeof(float)));
    CUDA_CHECK(cudaMemset(s->d_zl, 0, nk * sizeof(float)));

    /*  ||b||_inf per column, for each column's relative stopping test. */
    std::vector<float> b_norm(k, 1.f);
    for (std::size_t c = 0; c != k; ++c) {
        CUDA_CHECK(cudaMemset(s->d_nrm, 0, sizeof(float)));
        LAUNCH((max_abs_kernel<<<g, T>>>(n, s->d_bh + c * ld, s->d_nrm)));
        float v = 0.f;
        CUDA_CHECK(cudaMemcpy(&v, s->d_nrm, sizeof(float),
                              cudaMemcpyDeviceToHost));
        b_norm[c] = (v > 0.f)? v : 1.f;
    }
    s->mark(3);

    /*  Per-column refinement state. Every column is carried through every
        pass of the batched solve, but a column that has met its own test
        stops taking the correction -- so its answer is what the column
        loop would have produced, bit for bit, and the batching costs it
        only wasted work. */
    std::size_t const cap = 60;
    std::vector<double>      best(k, 1e30);
    std::vector<int>         stalled(k, 0);
    std::vector<char>        done(k, 0);
    std::vector<std::size_t> it_col(k, 0);

    for (std::size_t it = 0; it != cap; ++it) {

        for (std::size_t c = 0; c != k; ++c) {
            if (done[c])
                continue;
            LAUNCH((k_df_residual_warp<<<(n * 32 + T - 1) / T, T>>>(
                n, s->d_ah, s->d_al, s->d_xh + c * ld, s->d_xl + c * ld,
                s->d_bh + c * ld, s->d_bl + c * ld,
                s->d_rh + c * ld, s->d_rl + c * ld)));
        }

        std::size_t n_active = 0;
        for (std::size_t c = 0; c != k; ++c) {
            if (done[c])
                continue;
            CUDA_CHECK(cudaMemset(s->d_nrm, 0, sizeof(float)));
            LAUNCH((max_abs_kernel<<<g, T>>>(n, s->d_rh + c * ld,
                                             s->d_nrm)));
            float r_norm = 0.f;
            CUDA_CHECK(cudaMemcpy(&r_norm, s->d_nrm, sizeof(float),
                                  cudaMemcpyDeviceToHost));
            double const rel = static_cast<double>(r_norm) /
                               static_cast<double>(b_norm[c]);
            if (rel < 1e-14) {
                done[c] = 1;
                continue;
            }
            if (rel < 0.7 * best[c]) {
                best[c] = rel;
                stalled[c] = 0;
            } else if (++stalled[c] >= 2 && it > 3) {
                done[c] = 1;
                continue;
            }
            ++n_active;
        }
        s->mark(0);

        if (n_active == 0)
            break;

        /*  A converged column keeps its answer. The stationary path
            does that by skipping its update; the batched GMRES path
            runs every column at once, so the column is frozen instead
            by zeroing its residual -- B0^-1 0 is 0, beta is 0, the
            least squares sees an empty Krylov space, and the update it
            contributes is exactly zero. */
        if (inner_j > 0) {
            for (std::size_t c = 0; c != k; ++c)
                if (done[c]) {
                    CUDA_CHECK(cudaMemset(s->d_rh + c * ld, 0,
                                          n * sizeof(float)));
                    CUDA_CHECK(cudaMemset(s->d_rl + c * ld, 0,
                                          n * sizeof(float)));
                }
            s->mark(1);
            gmres_inner(s, n, static_cast<int>(k), static_cast<int>(ld),
                        inner_j, s->d_rh, s->d_rl, s->d_xh, s->d_xl);
            s->mark(2);
            for (std::size_t c = 0; c != k; ++c)
                if (!done[c])
                    ++it_col[c];
            s->mark(3);
            continue;
        }

        for (std::size_t c = 0; c != k; ++c) {
            if (done[c])
                continue;
            LAUNCH((gather_kernel<<<g, T>>>(n, s->d_perm,
                                            s->d_rh + c * ld,
                                            s->d_rl + c * ld,
                                            s->d_yh + c * ld,
                                            s->d_yl + c * ld)));
        }
        s->mark(1);

        /*  One batched pass over every column, converged ones included:
            compacting the active set would move columns in memory and
            buy nothing, since the pass is dominated by the shared walk
            over L\U rather than by the per-column arithmetic. */
        if (s->srung_ib != 0) {
            trsv_L_mrhs(n, 256, s->srung_ib, (int)k, (int)ld,
                        s->d_hi, s->d_lo, s->d_dlh, s->d_dll,
                        s->d_yh, s->d_yl, s->d_zh, s->d_zl,
                        s->d_th, s->d_tl);
            trsv_U_mrhs(n, 256, s->srung_ib, (int)k, (int)ld,
                        s->d_hi, s->d_lo, s->d_duh, s->d_dul,
                        s->d_zh, s->d_zl, s->d_yh, s->d_yl,
                        s->d_th, s->d_tl);
        } else {
            for (std::size_t c = 0; c != k; ++c) {
                if (done[c])
                    continue;
                trsv_L_blocked(n, 256, s->d_hi, s->d_lo,
                               s->d_yh + c * ld, s->d_yl + c * ld,
                               s->d_zh + c * ld, s->d_zl + c * ld,
                               s->d_th, s->d_tl);
                trsv_U_blocked(n, 256, s->d_hi, s->d_lo,
                               s->d_zh + c * ld, s->d_zl + c * ld,
                               s->d_yh + c * ld, s->d_yl + c * ld,
                               s->d_th, s->d_tl);
            }
        }
        s->mark(2);

        for (std::size_t c = 0; c != k; ++c) {
            if (done[c])
                continue;
            LAUNCH((add_correction_kernel<<<g, T>>>(
                n, s->d_yh + c * ld, s->d_yl + c * ld,
                s->d_xh + c * ld, s->d_xl + c * ld)));
            ++it_col[c];
        }
        s->mark(3);
    }

    for (std::size_t c = 0; c != k; ++c) {
        LAUNCH((combine_kernel<<<g, T>>>(n, s->d_xh + c * ld,
                                         s->d_xl + c * ld,
                                         d_x + c * s->n)));
        if (it_col[c] > used)
            used = it_col[c];
    }
    s->mark(3);

    double const ms = outer.stop();

    double *bucket[4] = {&s->times.residual, &s->times.gather,
                         &s->times.trsv,     &s->times.update};
    s->fold(bucket);

    if (n_iterations != nullptr)
        *n_iterations = used;

    return ms;
}

phase_times const &profile(state const *s) {

    static phase_times const empty = {};
    return (s != nullptr)? s->times : empty;
}

/*  Does the cascade in k_saturation actually reproduce k_slice_rows?

    Everything item 6 reports rests on that replication, and a
    replication is worth exactly as much as the check that it matches.
    The per-level SCALE is the signature: it is max|hi| / 127 over the
    row, and it is determined entirely by the residual cascade, so if
    every scale agrees bit for bit at every level then the residuals
    agree at every level and so does everything downstream.

    Compares against the vendored kernel on the real L21 block. Returns
    the number of differing scales. */
std::size_t saturation_verify(state *s, int const depth) {

    if (s == nullptr)
        return 1;

    int const n   = static_cast<int>(s->n);
    int const b   = (n < 256)? n : 256;
    int const r0  = b;
    int const mp  = n - r0;
    if (mp <= 0)
        return 1;

    std::int8_t *lq = nullptr;
    float       *ls = nullptr, *sc = nullptr;
    int         *d_last = nullptr, *d_uf = nullptr;
    float       *d_g = nullptr;
    CUDA_CHECK(cudaMalloc(&lq, static_cast<std::size_t>(depth) * mp * b));
    CUDA_CHECK(cudaMalloc(&ls, static_cast<std::size_t>(depth) * mp * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&sc, static_cast<std::size_t>(depth) * n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_last, n * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_uf, n * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_g, 2 * QLU_I0MAX * n * sizeof(float)));

    /*  The vendored slicer, on exactly the block the trailing update
        slices: rows [b, n) over columns [0, b). */
    LAUNCH((k_slice_rows<<<mp, 256>>>(n, r0, 0, mp, b, depth,
                                      s->d_hi, s->d_lo, lq, ls)));

    k_saturation<<<n, 256>>>(n, 0, b, depth, 127, s->d_hi, s->d_lo,
                             d_last, d_uf, d_g, nullptr, sc);
    KERNEL_CHECK();

    std::vector<float> h_ls(static_cast<std::size_t>(depth) * mp);
    std::vector<float> h_sc(static_cast<std::size_t>(depth) * n);
    CUDA_CHECK(cudaMemcpy(h_ls.data(), ls, h_ls.size() * sizeof(float),
                          cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_sc.data(), sc, h_sc.size() * sizeof(float),
                          cudaMemcpyDeviceToHost));

    std::size_t bad = 0;
    for (int lev = 0; lev != depth; ++lev)
        for (int i = 0; i != mp; ++i) {
            float const v = h_ls[static_cast<std::size_t>(lev) * mp + i];
            float const w = h_sc[static_cast<std::size_t>(lev) * n + r0 + i];
            if (v != w)
                ++bad;
        }

    cudaFree(lq); cudaFree(ls); cudaFree(sc);
    cudaFree(d_last); cudaFree(d_uf); cudaFree(d_g);
    return bad;
}

/*  Select the slicer's rounding mode for every subsequent factor.

    Global rather than per-state because the slicer is vendored and the
    flag lives beside it; there is one device symbol and it applies to
    whatever factors next. Calls are cheap and the gates set it
    explicitly on both sides rather than relying on the default. */
void set_rounding(rounding const r) {
    int const v = (r == rounding::stochastic)? 1 : 0;
    CUDA_CHECK(cudaMemcpyToSymbol(lps_sr_mode, &v, sizeof v));
}

void set_sr_stream(unsigned long long const stream) {
    CUDA_CHECK(cudaMemcpyToSymbol(lps_sr_stream, &stream, sizeof stream));
}

bool saturation(
    state      *s,
    int const   c0,
    int const   max_depth,
    int        *out,
    float      *g_max,
    int        *isat_i0,
    int const   qmax) {

    if (s == nullptr || out == nullptr)
        return false;

    int const n = static_cast<int>(s->n);
    int const width = (c0 + 256 <= n)? 256 : (n - c0);
    if (width <= 0)
        return false;

    int   *d_last = nullptr, *d_uf = nullptr, *d_si = nullptr;
    float *d_g = nullptr;
    if (!CUDA_CHECK(cudaMalloc(&d_last, n * sizeof(int))) ||
        !CUDA_CHECK(cudaMalloc(&d_uf, n * sizeof(int))) ||
        !CUDA_CHECK(cudaMalloc(&d_g, 2 * QLU_I0MAX * n * sizeof(float))) ||
        !CUDA_CHECK(cudaMalloc(&d_si, QLU_I0MAX * n * sizeof(int))))
        return false;

    k_saturation<<<n, 256>>>(n, c0, width, max_depth, qmax,
                             s->d_hi, s->d_lo, d_last, d_uf, d_g,
                             d_si, nullptr);
    KERNEL_CHECK();

    std::vector<int> uf(n);
    CUDA_CHECK(cudaMemcpy(out, d_last, n * sizeof(int),
                          cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(uf.data(), d_uf, n * sizeof(int),
                          cudaMemcpyDeviceToHost));
    if (g_max != nullptr)
        CUDA_CHECK(cudaMemcpy(g_max, d_g, 2 * QLU_I0MAX * n * sizeof(float),
                              cudaMemcpyDeviceToHost));
    if (isat_i0 != nullptr)
        CUDA_CHECK(cudaMemcpy(isat_i0, d_si, QLU_I0MAX * n * sizeof(int),
                              cudaMemcpyDeviceToHost));
    cudaFree(d_last);
    cudaFree(d_uf);
    cudaFree(d_g);
    cudaFree(d_si);

    /*  i_sat is one past the last level that changed anything. A row is
        valid unless its residual underflowed at or before that level --
        underflow afterwards just means an exhausted residual, which IS
        saturation. */
    bool clean = true;
    for (int i = 0; i != n; ++i) {
        if (uf[i] != 0 && uf[i] <= out[i])
            clean = false;
        out[i] += 1;
    }
    return clean;
}

void copy_factor(
    state *s,
    float *hi,
    float *lo,
    int   *perm) {

    if (s == nullptr)
        return;

    std::size_t const nn = s->n * s->n;
    CUDA_CHECK(cudaMemcpy(hi, s->d_hi, nn * sizeof(float),
                          cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(lo, s->d_lo, nn * sizeof(float),
                          cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(perm, s->d_perm, s->n * sizeof(int),
                          cudaMemcpyDeviceToHost));
}

} /* namespace qlu */
